use std::{fs, path::PathBuf};

fn root() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
}

#[test]
fn strict_role_free_interface_is_the_sole_schema_authority() {
    let root = root();
    let source =
        fs::read_to_string(root.join("ethos/interface.ethos")).expect("strict Interface exists");
    let generated =
        fs::read_to_string(root.join("src/schema/lib/generated.rs")).expect("projection exists");
    let manifest = fs::read_to_string(root.join("src/bootstrap_manifest.rs"))
        .expect("authority manifest exists");

    assert!(source.starts_with("Interface.{1 0 0}\n[]\n{\n  []\n  []\n  []\n  ["));
    assert!(source.contains("ComponentKind.["));
    assert!(source.contains("ComponentClassification.{"));
    assert!(!source.contains("Request"));
    assert!(!source.contains("Reply"));
    assert!(
        !root.join("schema").exists(),
        "legacy source tree must be absent"
    );
    assert!(generated.starts_with(
        "// @generated by schema-rust from an authority-verified bootstrap Interface"
    ));
    assert!(!generated.contains("ComponentKind"));
    assert!(!generated.contains("AuthorizedObjectInterest"));
    assert_eq!(manifest.matches("DeclarationSeat::new").count(), 38);
}

#[test]
fn cargo_metadata_publishes_the_owned_ethos_source() {
    let output = std::process::Command::new("cargo")
        .args(["metadata", "--format-version", "1", "--no-deps"])
        .output()
        .expect("run cargo metadata");
    assert!(output.status.success());
    let metadata = String::from_utf8(output.stdout).expect("metadata is UTF-8");
    assert!(metadata.contains("signal-standard"));

    let source = signal_standard::STANDARD_INTERFACE_SOURCE;
    assert_eq!(source, include_str!("../ethos/interface.ethos"));
    assert!(signal_standard::STANDARD_INTERFACE_RUST.starts_with("// @generated"));
}
