// @generated by schema-rust from an authority-verified bootstrap Interface

pub enum z2VWWD {z2VUqs , z2VZ4y , z2VSDw , z2VPLF , z2VPuL , z2Vc9t , z2VNYL , z2VVh8 , z2VbTm , z2VWoi , z2VZ73 , z2VPk8 , z2VN8F , z2VN71 ,} 
pub struct z2VTjK {
    pub field_0: z2VWWD,
    pub field_1: z2VSyM,
    pub field_2: z2Vbhy,
}
pub enum z2Vbhy {z2VYDX , z2VPDv , z2Ve6d , z2VV79 , z2Vd4Q ,} 
pub struct z2VdWE {
    pub field_0: z2VWWD,
    pub field_1: z2Vbhy,
}
pub struct z2VLyh(std::string::String);
impl z2VLyh {
    /// Construct the generated newtype from its source-declared payload.
    pub fn new(payload: std::string::String) -> Self {
        Self(payload)
    }
    /// Borrow the one source-declared payload without decoding archive bytes.
    pub fn payload(&self) -> &std::string::String {
        &self.0
    }
    /// Consume the newtype and recover its source-declared payload.
    pub fn into_payload(self) -> std::string::String {
        self.0
    }
}
pub struct z2VSyM(std::string::String);
impl z2VSyM {
    /// Construct the generated newtype from its source-declared payload.
    pub fn new(payload: std::string::String) -> Self {
        Self(payload)
    }
    /// Borrow the one source-declared payload without decoding archive bytes.
    pub fn payload(&self) -> &std::string::String {
        &self.0
    }
    /// Consume the newtype and recover its source-declared payload.
    pub fn into_payload(self) -> std::string::String {
        self.0
    }
}
pub enum z2VduW {z2VNCH ( z2VaVE ,) , z2VUkE ( z2VXNY ,) ,} 
pub enum z2VQD6 {z2VW1p ( z2VWWD ,) , z2VNut ( z2VdWE ,) , z2VYnk , z2Ve8W ( z2Vbhy ,) ,} 
pub struct z2VXNY(std::string::String);
impl z2VXNY {
    /// Construct the generated newtype from its source-declared payload.
    pub fn new(payload: std::string::String) -> Self {
        Self(payload)
    }
    /// Borrow the one source-declared payload without decoding archive bytes.
    pub fn payload(&self) -> &std::string::String {
        &self.0
    }
    /// Consume the newtype and recover its source-declared payload.
    pub fn into_payload(self) -> std::string::String {
        self.0
    }
}
pub struct z2VaVE {
    pub field_0: z2VLyh,
    pub field_1: z2VQaE,
}
pub struct z2VQaE(u64);
impl z2VQaE {
    /// Construct the generated newtype from its source-declared payload.
    pub fn new(payload: u64) -> Self {
        Self(payload)
    }
    /// Borrow the one source-declared payload without decoding archive bytes.
    pub fn payload(&self) -> &u64 {
        &self.0
    }
    /// Consume the newtype and recover its source-declared payload.
    pub fn into_payload(self) -> u64 {
        self.0
    }
}
pub struct z2VU3x {
    pub field_0: z2VSkP,
    pub field_1: z2VQD6,
}
pub struct z2VSkP {
    pub field_0: z2VWWD,
    pub field_1: z2Vbhy,
}
